### ISSUE TITLE
avoiding new extensions?

### ISSUE THREAD

**Issue by kberry** [jarnosz/blopentype#1]
Hi Luis - before I install blopentype in TeX Live, let me ask about the possibility of avoiding the new extensions (.ltx and .ltm) that you invented. Every new extension means more infrastructure setup, more confusion about "what does it mean", etc. There are already far too many LuaTeX-related extensions, so adding more for a couple of files seems suboptimal.

How about just blot-files-mac.lua and blot-fonts-script.lua, etc., if you want to make the distinction? I don't really understand what you mean by "scripts", either. Clearly they are not executables for the command line. (Which I am glad about. :)

THanks.

**Comment by lodwicz** [comment]
Hello! 

One thing I liked from Isambert's approach was to distinguish "regular" `.tex` files (which may run even in DEKTeX) from LuaTeX macros (which do include Lua code), on the one hand, and "regular" `.lua` code (which may make up regular Lua "modules", if indeed there is such a thing: lua was designed precisely to work as a "scripting" language for other programs) from Lua code specifically tied to LuaTeX. 

So the extensions `.ltm` and `.lts` were devised to mark precisely this distinction: LuaTeX *macros* (for the TeX side) and LuaTeX *scripts* (for the Lua side). It did not occur to me that these "scripts" could be interpreted as "executables"; perhaps *code* (LuaTeX code: `.ltc`) would have been a better choice. The distinction came to my mind from the several Perl extensions: `px` for executables, `pl` for libraries, `pm` for modules, and so forth.

I guess the TeXLive objection comes from the need to cater for these new filename extensions by `kpathsea`: in that case, I have no problem in renaming the files to `tex` and `lua`, respectively (the filenames don't intersect).

**Comment by lodwicz** [comment]
Done.

**Comment by kberry** [comment]
Thanks for renaming the files. If you push a new release to CTAN, I'll
go ahead and put it into TL.

I understand your (and Isambert's) point of view. From my point of view,
it's a feature, not a bug, to use the same extension for "regular"
macros and Lua-related macros, and everything else too. It's the usual
question of lumping vs. splitting ...

You don't need to have any particular directory structure (is that what
you meant by "branches"?) for the .tex and .lua files. I can just put
all the runtime files (your luatex/ subdir) in a single directory
tex/luatex/blopentype. That would be the simplest, and IMHO make the
files easiest to find (by users; kpathsea doesn't care :).

All the best,
karl

**Comment by lodwicz** [comment]
hello! the ctan team just pushed the fix into the archive without an announcement, per my request, as we just reset the initial release and the versioning system: you may check it in 24 h or so. cheers!

**Comment by kberry** [comment]
Hi Luis - I just imported it into TL for tonight's update. Thanks for
putting up with me :). -k
